#!/bin/bash
## tinify
## - tinifies images
## version 0.0.1 - initial
##################################################
. ${SH2}/error.sh 		# error handling 
. ${SH2}/aliases/commands.sh	# commands
. ${SH2}/cecho.sh		# colored echo
##################################################
file-info() { { local infile ; infile="${1}" ; }
 test "${infile}"
 file ${infile}
 du -d 0 -b ${infile}
}
tinify-api-shrink() { { local infile ; infile="${1}" ; }
  curl https://api.tinify.com/shrink \
  --user "api:${API_KEY}" \
  --dump-header header \
  --data-binary "@${infile}" \
  --silent
}
tinify-api-output() { { local inurl ; inurl="${1}" ; }
  curl ${inurl} \
  --user "api:${API_KEY}" \
  --dump-header header \
  --output optimized.jpg \
  --silent
}
tinify-api() {
 commands
}
tinify-image() { { local infile ; infile="${1}" ; }
 test -f "${infile}" || { 
   {
     echo file missing 
   } 1>&2
   false
 }
 cecho green "uploading file for compression ..."
 {
   tinify-api-shrink ${infile}
 } | tee response 
 compression_count=$( cat header | grep -e 'Compression-Count' | cut '-d:' '-f2' )
 compression_output_url=$( cat response | jq '.output.url' | cut '-d"' '-f2' )
 compression_size_in=$( cat response | jq '.input.size' | cut '-d"' '-f2' )
 compression_size_out=$( cat response | jq '.output.size' | cut '-d"' '-f2' )
 compression_size_diff=$(( ${compression_size_out} - ${compression_size_in} ))
 compression_ration=$( cat response | jq '.output.ratio' | cut '-d"' '-f2' )
 cecho green "downloading compression output ..."
 {
   tinify-api-output ${compression_output_url}
 } | tee response
 compression_count=$( cat header | grep -e 'Compression-Count' | cut '-d:' '-f2' )
 cecho yellow compression_count: ${compression_count}
 cecho yellow BEFORE $( file-info ${infile} )
 cecho yellow AFTER $( file-info optimized.jpg )
 true
}
tinify() {
 . $( dirname ${0} )/config.sh 2>/dev/null || {
   {
     echo missing config
   } 1>&2
   false
 }
 test "${API_KEY}"
 commands
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
tinify ${@}
##################################################
## generated by create-stub2.sh v0.1.1
## on Wed, 14 Nov 2018 11:36:46 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
