#!/bin/bash
## tinify
## - tinify api functions
## version 0.0.1 - initial
##################################################
tinify-api-shrink() { { local infile ; infile="${1}" ; }
  curl https://api.tinify.com/shrink \
  --user "api:${API_KEY}" \
  --dump-header header \
  --data-binary "@${infile}" \
  --silent
}
tinify-api-output() { { local inurl ; inurl="${1}" ; }
  curl ${inurl} \
  --user "api:${API_KEY}" \
  --dump-header header \
  --output optimized.jpg \
  --silent
}
tinify-api() {
 commands
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Wed, 14 Nov 2018 11:36:46 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
